version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - '80:80'
    volumes:
    - ./:/var/www
    depends_on:
      - php

  php:
    container_name: php
    build: ./php
    ports:
    - '9111:9000'
    volumes:
    - ./:/var/www

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - '5432:5432'
    environment:
      POSTGRES_DB: 'dev'
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_USER: 'dev'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'